version: '3.8'

services:
  timescale-db-crossing:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: border_crossing_db
    volumes:
      - timescale-db-crossing-data:/var/lib/postgresql/data
    restart: always

  border-crossing-be:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - timescale-db-crossing
    restart: on-failure

volumes:
  timescale-db-crossing: